### ISSUE TITLE
Curl request not working

### ISSUE THREAD

**Issue by anju-infracloud** [Lokanathreddy1/url_shortner_v1#1]
I ran `curl -X POST http://127.0.0.1:5000/url_shortner -d '{"url": "https://www.google.com"}'` as well as `curl -X POST http://127.0.0.1:5000/url_shortner -d '{"url": "https://www.facebook.com"}' -H "Content-Type: application/x-www-form-urlencoded"
both requests are throwing `Invalid URL` error.
Please update readme file with correct requests.

**Comment by Lokanathreddy1** [comment]
Hi,

Can you please try as below.

 curl -X POST http://127.0.0.1:5000/url_shortner -d 'url=
https://www.google.com'

Thanks and Regards,

Lokanath Reddy E
+918884885153

**Comment by Lokanathreddy1** [comment]
Curl request was not in proper format ..
